[package]
name = "ledger-hw-transport"
version = "0.1.0"
authors = ["Edouard Paris <m@edouard.paris>"]
edition = "2018"

[dependencies]
async-trait = "0.1.24"
ledger-hw = { path = "../ledger"}

[dev-dependencies]
futures-await-test = "0.3.0"
